version: '3'

volumes:
  static:
  certs:
  nginx_conf:

services:
  landing:
    restart: always
    build: ./landing/
    volumes:
      - static:/app/staticfiles  # Статика собирается в директорию '/app/staticfiles'

  gateway:
    depends_on:
      - landing
    build: ./nginx/
    ports:
      - "90:90"
      - "8443:443"  # Изменяем 443 на 8443, чтобы избежать конфликта
    volumes:
      - static:/static  # Nginx использует директорию '/static' для статики
      - certs:/etc/letsencrypt
      - nginx_conf:/etc/nginx/templates
