version: '3'

volumes:
  static:
  redirector_static:
  certs:
  nginx_conf:

services:
  landing:
    restart: always
    build: ./landing/
    volumes:
      - static:/app/staticfiles

  redirector:
    restart: always
    build: ./redirector/
    volumes:
      - static:/app/staticfiles

  gateway:
    depends_on:
      - landing
      - redirector
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - certs:/etc/letsencrypt
      - nginx_conf:/etc/nginx/templates